### PR TITLE
added docker install instructions

### PR DESCRIPTION
**Pull request by caseyjlaw**

### CODE REVIEW

**Comment by caseyjlaw** [comment]
I hope this is useful. It was fun to play with, at any rate. I haven't used markdown much, so there is something off with my code formatting.

**Comment by jdswinbank** [comment]
Thanks Casey! I definitely think this is useful. I wonder what the long term prospects are -- I'm guessing that you probably don't want to take responsibility for keeping your Docker image up to date as new versions of the software are released (do you!?), so we should probably add some sort of disclaimer to the docs.

I'll write some text to that effect and merge it when I get chance (ie, escape from my current meeting).

**Comment by caseyjlaw** [comment]
Glad it is useful. Please feel to edit as you like.
My hope is that using a dockerfile would make it more durable. If you see issues with a build, I am happy to update the file.

**Comment by jdswinbank** [comment]
Thanks Casey! Now merged. Sorry for the delay.

**Pull request merged**
